version: '3'
services:
  registry:
    image: registry:latest
    ports:
      - "6000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry
    volumes:
      - ./registry:/registry