services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: s.thiessen@makingyourmilescount.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5433:80"