services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file: ".env"
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data