services:
  registry:
    container_name: server
    restart: always
    image: registry.historyhall.org/historyhall-server
    environment:
      - TZ="America/Winnipeg"
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY="/data"
    volumes:
      - ./.env:/app/packages/server/.env
      - ./assets:/app/packages/server/assets
    ports:
      - "5001:5001"